- name: Create user
  user:
    name: "{{ user.username }}"
    comment: "{{ user.comment }}"
    password: "{{ user.password }}"
    shell: /bin/bash
    createhome: true
    groups: "{{ user.groups }}"
    append: true
    state: present
  when: ansible_os_family == 'Debian'

- name: Add user authorized keys
  ansible.posix.authorized_key:
    user: "{{ user.username }}"
    key: "{{ user.public_key }}"
    state: present
