- name: install updates
  apt:
    upgrade: dist
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: install common dependencies
  apt:
    pkg:
      - sudo
      - curl
      - vim
      - git
      - rsync
      - build-essential
      - gnupg
      - software-properties-common
    state: latest
    update_cache: true
  when: ansible_os_family == "Debian"

- name: ensure wheel group exists
  group:
    name: wheel
    state: present

- name: allow passwordless sudo for wheel group
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: '/usr/sbin/visudo -cf %s'
  
- include_tasks: create-user.yml
  vars:
    user: "{{ item }}"
  loop:
    - username: "{{ personal_user }}"
      password: "{{ personal_password }}"
      public_key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
      comment: 'personal'
      groups: 'wheel'
    - username: ansible
      password: "{{ ansible_password }}"
      public_key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/ansible_id_rsa.pub') }}"
      comment: 'ansible service'
      groups: 'wheel'