- name: create luxor
  hosts: babylon.agartha
  become: true
  remote_user: root
  gather_facts: false
  vars_files:
    - ../vars/secrets.yml
  tasks:
    # TODO: check for vm 900, add when condition to steps below

    - name: create luxor LXC
      proxmox:
        vmid: 200
        description: 'Automation server'
        hostname: luxor
        password: "{{ luxor_password }}"
        node: "{{ primary_pve_node }}"
        api_host: "{{ primary_pve_node + '.' + domain }}"
        api_user: "{{ api_user }}"
        api_token_id: "{{ api_token_id }}"
        api_token_secret: "{{ api_token_secret }}"
        ostemplate: 'local:vztmpl/debian-11-standard_11.6-1_amd64.tar.zst'
        cores: 1
        storage: ssd0
        disk: 'ssd0:16'
        memory: 2048
        swap: 2048
        netif: '{"net0":"name=eth0,gw=10.42.10.1,ip=10.42.10.26/24,bridge=vmbr0"}'
        nameserver: "{{ dns_server }}"
        searchdomain: "{{ domain }}"
        pubkey: "{{ ssh_pubkey }}"
        onboot: true
        unprivileged: true
        features:
          - nesting=1
        state: present
      register: luxor_create

    - name: wait for create to finish
      pause:
        seconds: 10
      when: luxor_create.changed

    - name: deploy luxor
      proxmox:
        hostname: luxor
        api_host: "{{ primary_pve_node + '.' + domain }}"
        api_user: "{{ api_user }}"
        api_token_id: "{{ api_token_id }}"
        api_token_secret: "{{ api_token_secret }}"
        unprivileged: true
        state: started
      when: luxor_create.changed
    
    - name: wait for boot to finish
      pause:
        seconds: 10
      when: luxor_create.changed

    - name: upgrade packages to resolve systemd + sshd crash problem
      shell: pct exec 200 -- bash -c "apt update && apt upgrade -y"
      changed_when: false
      when: luxor_create.changed
    
    - name: enable root ssh login
      shell: pct exec 200 -- bash -c "sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin prohibit-password/g' /etc/ssh/sshd_config"
      changed_when: false
      when: luxor_create.changed
    
    - name: enable ssh public key authentication
      shell: pct exec 200 -- bash -c "sed -i 's/#PubkeyAuthentication yes/PubkeyAuthentication yes/g' /etc/ssh/sshd_config"
      changed_when: false
      when: luxor_create.changed

    - name: restart luxor
      proxmox:
        hostname: luxor
        api_host: "{{ primary_pve_node + '.' + domain }}"
        api_user: "{{ api_user }}"
        api_token_id: "{{ api_token_id }}"
        api_token_secret: "{{ api_token_secret }}"
        unprivileged: true
        state: restarted
      changed_when: false
      when: luxor_create.changed

    - name: wait for ssh port available
      wait_for:
        host: luxor.agartha
        port: 22
        delay: 10
        state: started
        timeout: 300
      when: luxor_create.changed

# TODO: turn play above into role

- name: setup luxor ssh and users
  hosts: luxor.agartha
  become: true
  remote_user: root
  vars_files:
    - ../vars/secrets.yml
  roles:
    - ../roles/sshd
    - ../roles/common

- name: init packer and terraform
  hosts: luxor.agartha
  become: true
  gather_facts: false
  tasks:
    - name: install hashicorp gpg key
      shell: |
        wget -O- https://apt.releases.hashicorp.com/gpg |
        gpg --dearmor |
        sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
      changed_when: false

    - name: add hashicorp repo
      shell: |
        echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" |
        sudo tee /etc/apt/sources.list.d/hashicorp.list
      changed_when: false

    - name: install terraform and packer from hashicorp repo
      apt:
        pkg:
          - terraform
          - packer
        state: latest
        update_cache: true

    - name: push repo subdirectory to remote
      copy:
        src: ../../luxor
        dest: /home/ansible
        owner: ansible
        group: ansible
        mode: 0770
    
    # TODO: copy ansible private key to luxor

    - name: init packer and terraform
      shell: make init
      args:
        chdir: /home/ansible/luxor

- name: provision VM templates
  hosts: luxor.agartha
  become: true
  gather_facts: false
  tasks:
    - name: packer build
      shell: 'make || true' # avoid template exists error
      args:
        chdir: /home/ansible/luxor/packer
  # TODO: when

- name: configure VM template properties not supported by packer proxmox provider
  hosts: babylon.agartha
  become: true
  remote_user: root
  gather_facts: false
  tasks:
    - name: enable discard and ssd emulation for template disk
      lineinfile:
        path: /etc/pve/qemu-server/900.conf
        regexp: '^scsi0'
        line: 'scsi0: ssd0:vm-900-disk-0,discard=on,iothread=1,size=16G,ssd=1'

- name: provision VMs
  hosts: luxor.agartha
  become: true
  gather_facts: false
  tasks:
    - name: terraform provisioning
      shell: make
      args:
        chdir: /home/ansible/luxor/terraform
  # TODO: when
