- name: create luxor
  hosts: babylon.agartha
  become: true
  remote_user: root
  gather_facts: false
  vars_files:
    - ../vars/secrets.yml
  tasks:
    - name: create luxor LXC
      proxmox:
        vmid: 200
        description: 'Automation server'
        hostname: luxor
        password: "{{ luxor_password }}"
        node: "{{ primary_pve_node }}"
        api_host: "{{ primary_pve_node + '.' + domain }}"
        api_user: "{{ api_user }}"
        api_token_id: "{{ api_token_id }}"
        api_token_secret: "{{ api_token_secret }}"
        ostemplate: 'local:vztmpl/debian-11-standard_11.6-1_amd64.tar.zst'
        cores: 1
        storage: ssd0
        disk: 'ssd0:16'
        memory: 2048
        swap: 2048
        netif: '{"net0":"name=eth0,gw=10.42.10.1,ip=10.42.10.26/24,bridge=vmbr0"}'
        nameserver: "{{ dns_server }}"
        searchdomain: "{{ domain }}"
        pubkey: "{{ ssh_pubkey }}"
        onboot: true
        unprivileged: true
        features:
          - nesting=1
        state: present
      register: luxor_create

    - name: wait for create to finish
      pause:
        seconds: 10
      when: luxor_create.changed

    - name: deploy luxor
      proxmox:
        hostname: luxor
        api_host: "{{ primary_pve_node + '.' + domain }}"
        api_user: "{{ api_user }}"
        api_token_id: "{{ api_token_id }}"
        api_token_secret: "{{ api_token_secret }}"
        unprivileged: true
        state: started
      when: luxor_create.changed
    
    - name: wait for boot to finish
      pause:
        seconds: 10
      when: luxor_create.changed

    - name: upgrade packages
      shell: pct exec 200 -- bash -c "apt update && apt upgrade -y"
      changed_when: false
      when: luxor_create.changed
    
    - name: enable root ssh login
      shell: pct exec 200 -- bash -c "sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin prohibit-password/g' /etc/ssh/sshd_config"
      changed_when: false
      when: luxor_create.changed
    
    - name: enable ssh public key authentication
      shell: pct exec 200 -- bash -c "sed -i 's/#PubkeyAuthentication yes/PubkeyAuthentication yes/g' /etc/ssh/sshd_config"
      changed_when: false
      when: luxor_create.changed
    
    - name: fix sshd
      shell: pct exec 200 -- bash -c "echo 'RuntimeDirectoryPreserve=yes' >> /lib/systemd/system/ssh@.service"
      changed_when: false
      when: luxor_create.changed

    - name: restart luxor
      proxmox:
        hostname: luxor
        api_host: "{{ primary_pve_node + '.' + domain }}"
        api_user: "{{ api_user }}"
        api_token_id: "{{ api_token_id }}"
        api_token_secret: "{{ api_token_secret }}"
        unprivileged: true
        state: restarted
      changed_when: false
      when: luxor_create.changed

    - name: wait for ssh port available
      wait_for:
        host: luxor.agartha
        port: 22
        delay: 10
        state: started
        timeout: 300
      when: luxor_create.changed

- name: setup luxor ssh and users
  hosts: luxor.agartha
  become: true
  vars_files:
    - ../vars/secrets.yml
  roles:
    - ../roles/sshd
    - ../roles/common

- name: provision resources with packer and terraform
  hosts: luxor.agartha
  become: true
  gather_facts: false
  tasks:
    - name: check if packer and terraform is installed
      shell: command -v packer && command -v terraform > /dev/null 2>&1
      register: are_deps_installed
      ignore_errors: true
      changed_when: are_deps_installed.rc != 0

    - name: install hashicorp gpg key
      shell: |
        wget -O- https://apt.releases.hashicorp.com/gpg |
        gpg --dearmor |
        sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
      when: are_deps_installed.rc != 0

    - name: add hashicorp repo
      shell: |
        echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" |
        sudo tee /etc/apt/sources.list.d/hashicorp.list
      when: are_deps_installed.rc != 0

    - name: install terraform and packer from hashicorp repo
      apt:
        pkg:
          - terraform
          - packer
        state: latest
        update_cache: true
      when: are_deps_installed.rc != 0

    - name: push repo subdirectory to remote
      copy:
        src: ../../luxor
        dest: /home/ansible
        owner: ansible
        group: ansible
        mode: 0770

    - name: init packer and terraform
      make:
        chdir: /home/ansible/luxor
        target: init
      when: are_deps_installed.rc != 0

    - name: check if Debian VM template exists
      stat:
        path: /etc/pve/qemu-server/900.conf
      register: vm_900
      delegate_facts: true
      delegate_to: babylon.agartha

    - name: packer build
      make:
        chdir: /home/ansible/luxor/packer
        target: all
      when: not vm_900.stat.exists

    - name: enable discard and ssd emulation for template disk
      lineinfile:
        path: /etc/pve/qemu-server/900.conf
        regexp: '^scsi0'
        line: 'scsi0: ssd0:vm-900-disk-0,discard=on,iothread=1,size=16G,ssd=1'
      delegate_to: babylon.agartha

    - name: terraform provisioning
      make:
        chdir: /home/ansible/luxor/terraform
        target: all
      register: terraform_result
      changed_when: "'Resources: 0 added, 0 changed, 0 destroyed.' not in terraform_result.stdout"
