version: '3.9'

name: giza

x-logging: 
  &default-logging
    driver: "json-file"
    options:
      max-size: "100m"
      max-file: 3

services:
  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:v0.47.0
    ports:
      - '8085:8080'
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /cgroup:/cgroup:ro
    privileged: true
    devices:
      - /dev/kmsg:/dev/kmsg
    logging: *default-logging
    mem_limit: 256M
    restart: unless-stopped

  dashy:
    container_name: dashy
    image: lissy93/dashy:2.1.1
    ports:
      - '8082:80'
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./dashy/conf.yml:/app/public/conf.yml
      - ./dashy/entrypoint.sh:/entrypoint.sh
    env_file:
      - ./env/dashy.env
    command: ['/entrypoint.sh']
    logging: *default-logging
    restart: unless-stopped

  home-assistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:2023.3
    ports:
      - '8123:8123'
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - './home-assistant:/config'
    logging: *default-logging
    restart: unless-stopped

  jellyfin:
    container_name: jellyfin
    image: linuxserver/jellyfin:10.8.9
    ports:
      - '8096:8096'     # http web UI
      - '8920:8920'     # https web UI
      - '1900:1900/udp' # service discovery for DNLA and clients
      # - '7359:7359/udp' # client discovery on local network
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /mnt/docker/jellyfin/artwork:/artwork
      - /mnt/docker/jellyfin/config:/config
      - /mnt/docker/jellyfin/transcode:/transcode
      - /mnt/media/anime:/media/anime
      - /mnt/media/movies:/media/movies
      - /mnt/media/tv:/media/tv
    environment:
      - NVIDIA_VISIBLE_DEVICES=GPU-8d09812d-bf2a-aa91-11ea-3c212d4cb622
      # nvidia-smi --query-gpu=gpu_uuid --format=csv
      - DOTNET_SYSTEM_IO_DISABLEFILELOCKING=1
    env_file:
      - ./env/jellyfin.env
    logging: *default-logging
    restart: unless-stopped

  librespeed:
    container_name: librespeed
    image: linuxserver/librespeed:5.2.5
    ports:
      - '4080:80'
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /home/docker/data/librespeed:/config
    env_file:
      - ./env/librespeed.env
    logging: *default-logging
    restart: unless-stopped

  linkwarden:
    container_name: linkwarden
    image: ghcr.io/linkwarden/linkwarden:v2.5.3
    ports:
      - '8300:3000'
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /mnt/docker/linkwarden:/data/data
    env_file:
      - ./env/linkwarden.env
    logging: *default-logging
    restart: unless-stopped
    depends_on:
      - postgres
    
  mariadb:
    container_name: mariadb
    image: mariadb:10.7
    ports:
      - '3306:3306'
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - './mariadb/init-mariadb.sh:/docker-entrypoint-initdb.d/1-init.sh'
      - '/home/docker/data/mariadb:/var/lib/mysql'
    env_file:
      - ./env/mariadb.env
    logging: *default-logging
    restart: unless-stopped

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:2
    ports:
      - '1883:1883' # MQTT
      - '9011:9011' # MQTT over websocket
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - /home/docker/data/mosquitto/data:/mosquitto/data
      - /home/docker/data/mosquitto/logs:/mosquitto/log
    network_mode: host
    logging: *default-logging
    restart: unless-stopped

  nextcloud:
    container_name: nextcloud
    image: nextcloud:25.0-apache
    ports:
      - '8180:80'
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - '/home/docker/data/nextcloud/:/var/www/html'
    env_file:
      - ./env/nextcloud.env
    logging: *default-logging
    restart: unless-stopped
    depends_on:
      - mariadb

  node-exporter:
    container_name: node-exporter
    image: prom/node-exporter:v1.5.0
    ports:
      - '9100:9100'
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    logging: *default-logging
    mem_limit: 256M
    restart: unless-stopped

  portainer-agent:
    container_name: portainer-agent
    image: portainer/agent:2.17.1-alpine
    ports:
      - '9001:9001'
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    logging: *default-logging
    restart: unless-stopped

  postgres:
    container_name: postgres
    image: postgres:16-alpine
    ports:
      - '5432:5432'
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - '/home/docker/data/postgres:/var/lib/postgresql/data'
      - './postgres/init-postgres.sh:/docker-entrypoint-initdb.d/init.sh'
      - './postgres/postgresql.conf:/etc/postgres/postgresql.conf'
      # default: show config_file; /var/lib/postgresql/data/postgresql.conf
      - './postgres/pg_hba.conf:/etc/postgres/pg_hba.conf'
      # default: show hba_file; /var/lib/postgresql/data/pg_hba.conf
    env_file:
      - ./env/postgres.env
    command: 'postgres -c config_file=/etc/postgres/postgresql.conf'
    logging: *default-logging
    restart: unless-stopped

  promtail:
    container_name: promtail
    image: grafana/promtail:2.7.4
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/log:/ext_logs:ro
      - ./promtail/promtail.yml:/etc/promtail/config.yml
    environment:
      - HOSTNAME=giza
    command:
      - '-config.file=/etc/promtail/config.yml'
      - '-config.expand-env'
    logging: *default-logging
    mem_limit: 256M
    restart: unless-stopped

  ubooquity:
    container_name: ubooquity
    image: linuxserver/ubooquity:2.1.2
    ports:
      - '2202:2202' # library (/ubooquity)
      - '2203:2203' # admin (/ubooquity/admin)
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /home/docker/data/ubooquity:/config
      - /mnt/media/books/:/books
    environment:
      - MAXMEM=2048
    logging: *default-logging
    restart: unless-stopped
