version: '3.9'

services:
  diun:
    container_name: diun
    image: crazymax/diun:4
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /home/docker/data/diun:/data
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .diun.env
    restart: unless-stopped
