- name: Create user
  user:
    name: "{{ user_username }}"
    comment: "{{ user_comment }}"
    password: "{{ user_password }}"
    shell: "{{ user_shell }}"
    createhome: "{{ user_create_home }}"
    groups: "{{ user_groups }}"
    append: true
    state: present
  when: ansible_os_family == 'Debian'

- name: Add user authorized keys
  ansible.posix.authorized_key:
    user: "{{ user_username }}"
    key: "{{ user_ssh_pub }}"
    state: present