- name: add OS specific variables
  include_vars: "{{ ansible_os_family | lower }}.yml"

- name: install sshd for Debian
  apt:
    pkg: ["{{ sshd_pkg_name }}"]
    state: latest
    update_cache: true
  when: ansible_os_family == 'Debian'

- name: configure sshd
  template:
    src: sshd_config.j2
    dest: "{{ sshd_config_basedir }}/sshd_config"
    validate: "/usr/sbin/sshd -t -f %s"
  notify: restart_sshd
  
- name: enable sshd
  service:
    name: "{{ sshd_service_name }}"
    state: started
    enabled: true