global:

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'discord_webhook'

receivers:
  # - name: 'web.hook'
  #   webhook_configs:
  #     - url: 'http://0.0.0.0:5001/'

  - name: "discord_webhook"
    webhook_configs:
      - url: "http://discord-alerts:9094"
