- name: init primary proxmox node
  hosts: babylon.agartha
  become: true
  remote_user: root
  vars_files:
    - ../vars/secrets.yml
  roles:
    - name: update packages
      role: ../roles/update
      vars:
        update_auto_reboot: false
        update_send_alert: true
        update_discord_webhook: "{{ discord_webhook }}"

    - name: set time
      role: ../roles/time

    - name: configure sshd
      role: ../roles/sshd

    - name: add wheel group
      role: ../roles/wheel

    - name: add personal user
      role: ../roles/user
      vars:
        user_username: "{{ personal_user }}"
        user_comment: 'personal user'
        user_password: "{{ personal_password }}"
        user_groups: 'wheel'
        user_ssh_pub: "{{ personal_ssh_pub }}"

    - name: add ansible user
      role: ../roles/user
      vars:
        user_username: "{{ ansible_user }}"
        user_comment: 'ansible service user'
        user_groups: 'wheel'
        user_ssh_pub: "{{ ansible_ssh_pub }}"

  tasks:
    - name: install general dependencies
      apt:
        pkg:
          - sudo
          - curl
          - rsync
          - python3-pip
        state: latest
        update_cache: true

    - name: install python packages
      pip:
        name:
          - proxmoxer
          - requests