- name: provision core vms with terraform
  hosts: luxor.agartha
  become: true
  gather_facts: false
  tasks:
    - name: init terraform
      shell:
        cmd: terraform init
        chdir: /home/ansible/infra/luxor/terraform
      changed_when: false

    - name: validate terraform
      shell:
        cmd: terraform validate
        chdir: /home/ansible/infra/luxor/terraform
      changed_when: false

    - name: apply terraform
      shell:
        cmd: terraform apply -auto-approve -parallelism 2
        chdir: /home/ansible/infra/luxor/terraform
      register: terraform_result
      changed_when: "'Resources: 0 added, 0 changed, 0 destroyed.' not in terraform_result.stdout"
