- name: configure babylon proxmox node
  import_playbook: config_babylon.yml

- name: provision and configure luxor server
  import_playbook: provision_luxor.yml

- name: provision vm templates
  import_playbook: provision_vm_templates.yml

- name: provision and configure core VMs
  import_playbook: provision_vms.yml

- name: start/configure docker containers on core VMs
  import_playbook: core_docker.yml

- name: configure main Portainer instance on athens
  import_playbook: athens_portainer.yml
