- name: init primary proxmox node
  hosts: babylon.agartha
  become: true
  remote_user: root
  vars_files:
    - ../vars/secrets.yml
  roles:
    - name: configure sshd
      role: ../roles/sshd

    - name: add wheel group
      role: ../roles/wheel

    - name: add personal user
      role: ../roles/user
      vars:
        user: "{{ personal_user }}"
        comment: 'personal user'
        password: "{{ personal_password }}"
        user_groups: 'wheel'
        ssh_pub: "{{ personal_ssh_pub }}"

    - name: add ansible user
      role: ../roles/user
      vars:
        user: "{{ ansible_user }}"
        comment: 'ansible service user'
        user_groups: 'wheel'
        ssh_pub: "{{ ansible_ssh_pub }}"

  tasks:
    - name: install general dependencies
      apt:
        pkg:
          - sudo
          - curl
          - rsync
          - python3-pip
        state: latest
        update_cache: true

    - name: install python packages
      pip:
        name:
          - proxmoxer
          - requests

- name: provision and configure luxor server
  import_playbook: provision_luxor.yml

- name: provision vm templates
  import_playbook: provision_vm_templates.yml

- name: provision and configure core VMs
  import_playbook: provision_vms.yml

- name: start/configure docker containers on core VMs
  import_playbook: core_docker.yml

- name: configure main Portainer instance on athens
  import_playbook: athens_portainer.yml
