- name: Root user tasks
  hosts: docker
  become: true
  vars_files: 
    - ../vars/secrets.yml
  vars:
    ansible_ssh_user: root
  tasks:
    - ping:
    - include_tasks: ../tasks/update/update.yml
    - include_tasks: ../tasks/user/create-wheel-group.yml
    - include_tasks: ../tasks/user/create-user.yml
      vars:
        - user: "{{ item }}"
      loop:
        - username: barrett
          password: "{{ personal_password }}"
          public_key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
          comment: 'personal'
          groups: 'wheel'
        - username: ansible
          password: "{{ ansible_password }}"
          public_key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/ansible_id_rsa.pub') }}"
          comment: 'ansible service'
          groups: 'wheel'
        - username: docker
          password: "{{ docker_password }}"
          public_key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/docker_id_rsa.pub') }}"
          comment: 'docker service'
          groups: 'wheel'
    - include_tasks: ../tasks/ssh/disable-password-auth.yml

# TODO: idk maybe roles cleaner than this...

- name: Ansible user tasks
  hosts: carthage.agartha
  become: true
  roles:
    - role: geerlingguy.docker
      vars:
        docker_users: ['docker', 'barrett']
  tasks:
    - name: Install NFS dependencies
      apt:
        pkg: [nfs-common]
        state: latest
        update_cache: true
    
    - name: Create docker volume directory
      file:
        path: /mnt/docker
        state: directory

    - name: Add TrueNAS NFS mount for docker volumes
      lineinfile:
        path: /etc/fstab
        state: present
        line: "service.truenas.agartha:/mnt/mesopotamia/nfs/proxmox/docker /mnt/docker nfs rw,soft,intr,nfsvers=4,rsize=8192,wsize=8192,timeo=14 0 0"

    - name: Mount fstab entries
      command: 'mount -av'
