- name: Disable password authentication for all users
  lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - regexp: '^PermitRootLogin'
      line: 'PermitRootLogin prohibit-password'
    - regexp: '^PasswordAuthentication'
      line: 'PasswordAuthentication No'
