version: '3.9'

name: jericho

x-logging: 
  &default-logging
    driver: "json-file"
    options:
      max-size: "100m"
      max-file: 3

services:
  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:v0.47.0
    ports:
      - '8085:8080'
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /cgroup:/cgroup:ro
    privileged: true
    devices:
      - /dev/kmsg:/dev/kmsg
    logging: *default-logging
    restart: unless-stopped

  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    image: jc21/nginx-proxy-manager:2.9.22
    ports:
      - '80:80'
      - '443:443'
      - '81:81' # admin ui
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./nginx/data:/data
      - ./letsencrypt:/etc/letsencrypt
    environment:
      - DISABLE_IPV6=true
    healthcheck:
      test: ["CMD", "/bin/check-health"]
      interval: 10s
      timeout: 3s
    logging: *default-logging
    restart: unless-stopped

  node-exporter:
    container_name: node-exporter
    image: prom/node-exporter:v1.5.0
    ports:
      - '9100:9100'
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    logging: *default-logging
    restart: unless-stopped

  portainer-agent:
    container_name: portainer-agent
    image: portainer/agent:2.17.1-alpine
    ports:
      - '9001:9001'
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    logging: *default-logging
    restart: unless-stopped

  promtail:
    container_name: promtail
    image: grafana/promtail:2.7.4
    ports:
      - '1514:1514/tcp'
      - '1514:1514/udp'
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/log:/ext_logs:ro
      - ./promtail/promtail.yml:/etc/promtail/config.yml
    environment:
      - HOSTNAME=jericho
    command:
      - '-config.file=/etc/promtail/config.yml'
      - '-config.expand-env'
    logging: *default-logging
    restart: unless-stopped
