global:
  scrape_interval: 20s

rule_files:
  - alert_rules.yml

scrape_configs:
  - job_name: cadvisor
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          host: carthage.agartha

  - job_name: node-exporter
    static_configs:
      - targets: ['node-exporter:9100']
  
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: pushgateway
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']

  - job_name: graphite-exporter
    honor_labels: true
    static_configs:
      - targets: ['graphite-exporter:9108']

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: ['alertmanager:9093']
