global:
  scrape_interval: 20s

rule_files:
  - alert_rules.yml

scrape_configs:
  - job_name: cadvisor
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          host: carthage.agartha
  
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: pushgateway
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']

  # core vms

  - job_name: athens
    honor_labels: true
    static_configs:
      - targets: ['athens.agartha:9100']

  - job_name: carthage
    honor_labels: true
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: giza
    honor_labels: true
    static_configs:
      - targets: ['giza.agartha:9100']
  
  - job_name: jericho
    honor_labels: true
    static_configs:
      - targets: ['jericho.agartha:9100']

  - job_name: rhodes
    honor_labels: true
    static_configs:
      - targets: ['rhodes.agartha:9100']

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: ['alertmanager:9093']
