global:
  scrape_interval: 30s

rule_files:
  - alert_rules.yml

scrape_configs:
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: node-exporter
    scrape_interval: 5s
    static_configs:
      - targets: ['node_exporter:9100']
  
  - job_name: prometheus
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: pushgateway
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: ['alertmanager:9093']
