agartha:
  hosts:
  children:
    proxmox:
      hosts:
        babylon.agartha:
        sumer.agartha:

    debian:
      hosts:
        octoprint.agartha:
        pihole.agartha:
      children:
        proxmox:

    free_bsd:
      hosts:
        truenas.agartha:

    ansible_test:
      hosts:
        10.42.30.60:
