- name: init primary proxmox node
  hosts: babylon.agartha
  become: true
  remote_user: root
  vars_files:
    - vars/secrets.yml
  roles:
    - role: sshd
    - role: wheel

    - role: user
      vars:
        user: "{{ personal_user }}"
        comment: 'personal user'
        password: "{{ personal_password }}"
        user_groups: 'wheel'
        ssh_pub: "{{ personal_ssh_pub }}"

    - role: user
      vars:
        user: "{{ ansible_user }}"
        comment: 'ansible service user'
        user_groups: 'wheel'
        ssh_pub: "{{ ansible_ssh_pub }}"

  tasks:
    - name: install general dependencies
      apt:
        pkg:
          - sudo
          - curl
          - python3-pip
        state: latest
        update_cache: true

    - name: install python packages
      pip:
        name:
          - proxmoxer
          - requests

- name: provision and configure luxor server
  import_playbook: playbooks/luxor.yml

- name: provision core VMs with packer and terraform on luxor
  import_playbook: playbooks/core_vms.yml
