- name: Update repos and cache
  apt:
    update_cache: true
    force_apt_get: true
    cache_valid_time: 3600

- name: Upgrade all packages
  apt:
    upgrade: dist
    force_apt_get: true

- name: Check for reboot
  stat:
    path: /var/run/reboot-required
    get_md5: false
  register: reboot_required

- name: Reboot if kernel updates need installed
  reboot:
    msg: "Reboot started by Ansible to install kernel updates"
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime
  when: reboot_required.stat.exists
