- name: Validate Discord alert configuration
  assert:
    that: (update_discord_webhook | length) > 0
    fail_msg: 'update_discord_webhook must be defined to send Discord alerts.'
  when: update_send_alert

- name: Update repos and cache
  apt:
    update_cache: true
    force_apt_get: true
    cache_valid_time: "{{ update_cache_valid_time }}"

- name: Upgrade all packages
  apt:
    force_apt_get: true
    state: latest

- name: Check for reboot
  stat:
    path: /var/run/reboot-required
    get_md5: false
  register: reboot_required

- name: Notify reboot handler
  debug:
    msg: 'Notifying reboot handler'
  changed_when: reboot_required.stat.exists
  notify: handle reboot
