version: '3.9'

name: rhodes

x-logging: 
  &default-logging
    driver: "json-file"
    options:
      max-size: "100m"
      max-file: 3

services:
  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:v0.47.0
    ports:
      - '8085:8080'
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /cgroup:/cgroup:ro
    privileged: true
    devices:
      - /dev/kmsg:/dev/kmsg
    logging: *default-logging
    mem_limit: 256M
    restart: unless-stopped

  node-exporter:
    container_name: node-exporter
    image: prom/node-exporter:v1.5.0
    ports:
      - '9100:9100'
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    logging: *default-logging
    mem_limit: 256M
    restart: unless-stopped

  portainer-agent:
    container_name: portainer-agent
    image: portainer/agent:2.17.1-alpine
    ports:
      - '9001:9001'
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    logging: *default-logging
    restart: unless-stopped

  promtail:
    container_name: promtail
    image: grafana/promtail:2.7.4
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/log:/ext_logs:ro
      - ./promtail/promtail.yml:/etc/promtail/config.yml
    environment:
      - HOSTNAME=rhodes
    command:
      - '-config.file=/etc/promtail/config.yml'
      - '-config.expand-env'
    logging: *default-logging
    mem_limit: 256M
    restart: unless-stopped

  prowlarr:
    container_name: prowlarr
    image: linuxserver/prowlarr:1.5.1-nightly
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /home/docker/data/prowlarr:/config
    security_opt:
      - no-new-privileges:true
    network_mode: service:transmission-openvpn
    logging: *default-logging
    restart: unless-stopped
    depends_on:
      - transmission-openvpn

  radarr:
    container_name: radarr
    image: linuxserver/radarr:4.5.2-nightly
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /home/docker/data/radarr:/config
      - /mnt/docker/radarr/MediaCover:/config/MediaCover
      - /mnt/docker/downloads/completed:/data/completed
      - /mnt/media/movies:/movies
    security_opt:
      - no-new-privileges:true
    network_mode: service:transmission-openvpn
    logging: *default-logging
    restart: unless-stopped
    depends_on:
      - transmission-openvpn
      - prowlarr

  readarr:
    container_name: readarr
    image: linuxserver/readarr:amd64-0.1.5-nightly
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /home/docker/data/readarr:/config
      - /mnt/docker/downloads/completed:/data/completed
      - /mnt/media/books:/books
    security_opt:
      - no-new-privileges:true
    network_mode: service:transmission-openvpn
    logging: *default-logging
    restart: unless-stopped
    depends_on:
      - transmission-openvpn
      - prowlarr

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:3.0.10
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /home/docker/data/sonarr:/config
      - /mnt/docker/sonarr/MediaCover:/config/MediaCover
      - /mnt/docker/downloads/completed:/data/completed
      - /mnt/media/anime:/anime
      - /mnt/media/tv:/tv
    security_opt:
      - no-new-privileges:true
    network_mode: service:transmission-openvpn
    logging: *default-logging
    restart: unless-stopped
    depends_on:
      - transmission-openvpn
      - prowlarr

  transmission-openvpn:
    container_name: transmission-openvpn
    image: haugene/transmission-openvpn:5.0
    ports:
      - 9091:9091 # transmission
      - 9696:9696 # prowlarr
      - 8787:8787 # readarr
      - 7878:7878 # radarr
      - 8989:8989 # sonarr
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /mnt/docker/downloads:/data
      - /mnt/docker/torrents:/media/torrents
      - /mnt/docker/transmission/config:/config
      - /mnt/docker/transmission/watch:/data/watch
    security_opt:
      - no-new-privileges:true
    env_file:
      - ./env/transmission.env
    cap_add:
      - NET_ADMIN
    sysctls:
      - "net.ipv6.conf.all.disable_ipv6=1"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    logging: *default-logging
    restart: unless-stopped
